"""
考研英语核心词库自动生成器
=================================
1. 从内置高频词表出发（覆盖考研大纲核心1500+词）
2. 通过免费 Dictionary API (dictionaryapi.dev) 获取音标 + 英文释义
3. 结合内置考研中文释义，生成完整的 kaoyan.json
4. 无需 LLM API Key，完全免费

用法：
  python scripts/generate_kaoyan_wordbank.py              # 生成全部
  python scripts/generate_kaoyan_wordbank.py --count 100  # 只生成前100个
  python scripts/generate_kaoyan_wordbank.py --batch A    # 只生成A开头
"""
import sys, os, io, json, time, re
from pathlib import Path

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))
sys.stdout = io.TextIOWrapper(sys.stdout.buffer, encoding='utf-8')

import httpx
from backend.config import DATA_DIR, KAOYAN_WORDS_FILE

# ============================================================
# 考研英语高频核心词表（词 + 考研核心中文释义）
# 覆盖考纲核心词汇，按字母分组
# ============================================================

KAOYAN_VOCAB = {
    # ---- A ----
    "abandon": "v.放弃，抛弃；n.放纵，放任 【熟词僻义：放纵】",
    "abide": "v.忍受，容忍；遵守(by)",
    "ability": "n.能力，才能；本领",
    "abnormal": "adj.反常的，异常的",
    "aboard": "adv./prep.在船/飞机/车上",
    "abolish": "v.废除，取消（法律/制度）",
    "abroad": "adv.在国外，到国外；广泛流传",
    "absence": "n.缺席，不在；缺乏",
    "absolute": "adj.绝对的，完全的；专制的",
    "absorb": "v.吸收；吸引（注意力）；理解",
    "abstract": "adj.抽象的；n.摘要；v.提取",
    "absurd": "adj.荒谬的，不合理的",
    "abundant": "adj.丰富的，充裕的",
    "abuse": "v./n.滥用；虐待；辱骂",
    "academic": "adj.学术的；学院的；理论上的",
    "accelerate": "v.（使）加速，加快",
    "accent": "n.口音，腔调；重音；重点",
    "acceptance": "n.接受，接纳；认可",
    "access": "n.进入；使用权；v.获取，访问",
    "accommodate": "v.容纳；适应；提供食宿 【拼写：双c双m】",
    "accompany": "v.陪伴；伴随；为…伴奏",
    "accomplish": "v.完成，实现，达成",
    "account": "n.账户；叙述；v.解释(account for)；占据比例 【熟词僻义】",
    "accumulate": "v.积累，积聚",
    "accurate": "adj.准确的，精确的",
    "accuse": "v.指控，指责(accuse sb of)",
    "achieve": "v.取得，实现，完成",
    "acknowledge": "v.承认；确认收到；感谢",
    "acquaint": "v.使熟悉，使了解(acquaint sb with)",
    "acquire": "v.获得；习得（知识/技能）",
    "activate": "v.激活，使活跃",
    "acute": "adj.急性的；敏锐的；尖锐的",
    "adapt": "v.（使）适应；改编",
    "addict": "n.成瘾者；v.使上瘾 【熟词僻义：be addicted to 沉迷于】",
    "adequate": "adj.足够的；尚可的",
    "adhere": "v.黏附；遵守，坚持(adhere to)",
    "adjacent": "adj.邻近的，毗邻的",
    "adjust": "v.调整，调节；（使）适应",
    "administration": "n.管理，行政；管理部门；政府",
    "admire": "v.钦佩，赞赏",
    "admit": "v.承认；准许进入；容纳 【熟词僻义：准许进入】",
    "adolescent": "n.青少年；adj.青春期的",
    "adopt": "v.采用，采纳；收养 【易混：adapt适应】",
    "adverse": "adj.不利的，有害的；相反的",
    "advocate": "v.提倡，主张；n.倡导者",
    "affair": "n.事务；事件；(pl.)公共事务",
    "affection": "n.喜爱，感情，爱慕之情",
    "affiliate": "v.使隶属，使加入；n.附属机构",
    "affirm": "v.断言，肯定，确认",
    "aggravate": "v.加重，使恶化；激怒",
    "aggressive": "adj.侵略的；好斗的；有进取心的",
    "agitate": "v.搅动；使不安；鼓动",
    "agony": "n.（精神或肉体的）极度痛苦",
    "alert": "adj.警觉的；v.使警惕；n.警报",
    "alien": "adj.外国的；陌生的；n.外星人",
    "allege": "v.断言，宣称，指控",
    "allocate": "v.分配，分派",
    "allowance": "n.津贴，补贴；限额(make allowance for 考虑到)",
    "ally": "n.同盟国，盟友；v.结盟",
    "alter": "v.改变，变更，修改",
    "alternative": "adj.替代的；n.替代选择",
    "amateur": "n.业余爱好者；adj.业余的",
    "ambiguous": "adj.模棱两可的，含糊不清的",
    "ambition": "n.雄心，野心；追求的目标",
    "amend": "v.修改，修订（法律/文件）",
    "ample": "adj.充足的，丰富的；宽敞的",
    "analogy": "n.类比，比喻；类似(by analogy)",
    "analyze": "v.分析，解析",
    "ancestor": "n.祖先，祖宗",
    "anchor": "n.锚；支柱；新闻主播；v.固定",
    "anniversary": "n.周年纪念日",
    "annual": "adj.每年的，一年一度的；n.年刊",
    "anonymous": "adj.匿名的，无名的",
    "anticipate": "v.预期，期望；抢先行动",
    "anxiety": "n.焦虑，忧虑；渴望",
    "apparent": "adj.明显的，表面上的 【熟词僻义：表面上的≠真正的】",
    "appeal": "v./n.呼吁；吸引；上诉(appeal to)",
    "appetite": "n.食欲；欲望，爱好(appetite for)",
    "appliance": "n.家用电器，器具",
    "appreciate": "v.欣赏；感激；理解；增值 【熟词僻义：增值】",
    "approach": "v.接近，靠近；n.方法，途径",
    "appropriate": "adj.适当的；v.挪用，占用 【熟词僻义：挪用】",
    "approve": "v.批准，通过；赞成(approve of)",
    "approximate": "adj.大约的，近似的",
    "arbitrary": "adj.随意的，专断的，任意的",
    "arise": "v.产生，出现；（由…）引起(arise from)",
    "arouse": "v.引起，唤起；唤醒",
    "array": "n.一系列，大量；数组；排列",
    "articulate": "v.清晰表达；adj.口齿清晰的",
    "ascend": "v.上升，攀登",
    "aspect": "n.方面；外观，面貌",
    "aspire": "v.渴望，追求(aspire to)",
    "assault": "n./v.（武力/口头上的）攻击",
    "assemble": "v.集合，聚集；组装",
    "assert": "v.断言，声称；维护，坚持",
    "assign": "v.分配，指派；确定（时间/价值）",
    "assimilate": "v.（使）同化；吸收，消化",
    "associate": "v.联系，关联；n.同事；adj.副的",
    "assume": "v.假设，认为；承担；呈现 【熟词僻义：承担/呈现】",
    "assure": "v.向…保证，使确信",
    "atmosphere": "n.大气层；氛围，气氛",
    "attach": "v.附上，系上；使依恋(attach importance to 重视)",
    "attain": "v.达到，获得，实现",
    "attendance": "n.出席，参加；出勤率",
    "attitude": "n.态度，看法；姿势",
    "attribute": "v.归因于(attribute to)；n.属性，特性",
    "authentic": "adj.真正的，真实的；可信的",
    "authority": "n.权威；权力；当局(authorities)",
    "automate": "v.使自动化",
    "autonomy": "n.自治，自治权；自主",
    "avail": "v.利用(avail oneself of)；n.效用(to no avail 徒劳)",
    "avenue": "n.林荫大道；途径，方法",
    "avert": "v.防止，避免；转移（目光）",
    "award": "n.奖，奖品；v.授予，给予",

    # ---- B ----
    "bachelor": "n.学士；单身汉",
    "backward": "adj.向后的；落后的",
    "baffle": "v.使困惑，难住",
    "bankrupt": "adj.破产的；n.破产者",
    "bargain": "n.便宜货；协议；v.讨价还价",
    "barren": "adj.贫瘠的；不育的",
    "barrier": "n.障碍物，壁垒；屏障",
    "bearing": "n.关系，影响(have bearing on)；举止，风度",
    "beforehand": "adv.预先，事先",
    "behalf": "n.代表(on behalf of)",
    "behave": "v.表现得体，行为规矩",
    "bewilder": "v.使迷惑，使糊涂",
    "bias": "n.偏见，偏向；v.使有偏见",
    "bind": "v.捆绑；约束；装订",
    "bizarre": "adj.奇异的，古怪的",
    "blame": "v.责备，责怪；n.责任",
    "blend": "v.混合，融合；n.混合物",
    "bloom": "v.开花，绽放；n.花，盛开的时期",
    "blueprint": "n.蓝图，行动计划",
    "blunder": "n.大错误；v.犯大错",
    "blunt": "adj.钝的；直率的；v.使减弱",
    "bonus": "n.奖金，红利；额外的好处",
    "boom": "n./v.繁荣，兴旺；发出隆隆声",
    "boost": "v./n.促进，提高；推动",
    "bound": "adj.一定会(bound to)；n.边界(pl.)；v.跳跃",
    "boycott": "v./n.抵制，拒绝购买",
    "breach": "n.违反，破坏；缺口；v.违反",
    "breakdown": "n.故障；崩溃；分解",
    "breed": "v.繁殖；养育；n.品种",
    "bribe": "n.贿赂；v.向…行贿",
    "brief": "adj.简短的；v.向…简要介绍",
    "brilliant": "adj.杰出的，出色的；明亮的",
    "brisk": "adj.轻快的；兴隆的；清新的",
    "brittle": "adj.易碎的；脆弱的",
    "budget": "n.预算；v.编预算，为…做预算",
    "bulk": "n.大部分(bulk of)；大体积(in bulk 大批)",
    "bureaucracy": "n.官僚主义，官僚机构",
    "burial": "n.埋葬，葬礼",
    "bypass": "v.绕过，回避；n.旁路",

    # ---- C ----
    "cabinet": "n.内阁；橱柜",
    "campaign": "n.运动（政治/商业）；战役",
    "candidate": "n.候选人；应试者",
    "capacity": "n.容量；能力；身份(in one's capacity as)",
    "captive": "n.俘虏；adj.被俘虏的，被迷住的",
    "capture": "v.捕获，俘获；n.俘获",
    "carbon": "n.碳(carbon dioxide 二氧化碳)",
    "cardinal": "adj.最重要的，基本的",
    "career": "n.职业，生涯",
    "casual": "adj.随便的；偶然的；临时的",
    "casualty": "n.伤亡人员；受害者",
    "catalog": "n.目录；v.编目录",
    "catastrophe": "n.大灾难，惨败",
    "category": "n.种类，类别",
    "cater": "v.满足需求(cater to/for)；提供餐饮",
    "caution": "n.小心，谨慎；警告；v.警告",
    "cease": "v.停止，终止",
    "challenge": "n./v.挑战；质疑",
    "champion": "n.冠军；拥护者；v.拥护",
    "channel": "n.频道；渠道；海峡；v.引导",
    "chaos": "n.混乱，无秩序",
    "character": "n.性格；特点；人物角色；字",
    "characterize": "v.以…为特征；描述…的特性",
    "charity": "n.慈善，慈善机构；宽容",
    "chart": "n.图表；v.绘制图表；规划",
    "charter": "n.宪章；特许状；v.特许，包租",
    "cherish": "v.珍爱，珍惜；怀有（希望）",
    "chronic": "adj.慢性的；长期的",
    "circuit": "n.电路；环行；巡回",
    "circulate": "v.（使）循环；（使）流传",
    "circumstance": "n.环境，情况；(pl.)经济状况",
    "cite": "v.引用，引证；表彰",
    "civilian": "n.平民；adj.平民的",
    "civilization": "n.文明，文化",
    "claim": "v./n.声称，主张；索取，索赔",
    "clarify": "v.澄清，阐明",
    "clash": "n./v.冲突；碰撞；不协调",
    "classic": "adj.经典的；n.经典作品",
    "classify": "v.分类，归类",
    "clause": "n.从句；条款",
    "client": "n.客户，委托人",
    "climate": "n.气候；风气，氛围",
    "cling": "v.紧紧抓住；坚持(cling to)；依恋",
    "clue": "n.线索，提示",
    "cluster": "n.群，簇；v.聚集",
    "coalition": "n.联盟，联合体",
    "coarse": "adj.粗糙的；粗俗的",
    "cognitive": "adj.认知的，认识的",
    "coherent": "adj.连贯的，一致的；有条理的",
    "coincide": "v.同时发生；相符(coincide with)",
    "collaborate": "v.合作，协作；通敌",
    "collapse": "v./n.倒塌；崩溃；暴跌",
    "combat": "n./v.战斗，斗争；防止",
    "commence": "v.开始，着手",
    "commend": "v.表扬，称赞；推荐",
    "commentary": "n.评论，注释；实况报道",
    "commit": "v.犯（罪/错）；承诺(commit to)；投入",
    "commodity": "n.商品，货物",
    "commonplace": "adj.平凡的，普通的；n.常见的事",
    "communicate": "v.交流，沟通；传达；传染",
    "community": "n.社区，社会；团体",
    "companion": "n.同伴，伴侣",
    "comparable": "adj.可比较的；比得上的",
    "compel": "v.强迫，迫使",
    "compensate": "v.补偿，弥补(compensate for)",
    "compete": "v.竞争，比赛",
    "competent": "adj.有能力的，胜任的",
    "compile": "v.编纂，汇编",
    "complement": "n.补充物；v.补充 【易混：compliment 赞扬】",
    "complex": "adj.复杂的；n.综合体，建筑群",
    "complicate": "v.使复杂化",
    "comply": "v.遵守，服从(comply with)",
    "compose": "v.组成；创作；使平静",
    "compound": "n.化合物；复合词；adj.复合的",
    "comprehend": "v.理解，领悟",
    "comprehensive": "adj.全面的，综合的",
    "compress": "v.压缩，压紧",
    "comprise": "v.包含，由…组成",
    "compromise": "n./v.妥协，让步；损害",
    "compulsory": "adj.强制性的，义务的",
    "conceal": "v.隐藏，隐瞒",
    "concede": "v.（勉强）承认；让步",
    "conceive": "v.构想，想象(conceive of)；怀孕",
    "concentrate": "v.集中，专心；浓缩",
    "concept": "n.概念，观念",
    "concise": "adj.简洁的，简明的",
    "concrete": "adj.具体的；n.混凝土",
    "condemn": "v.谴责，指责；判刑",
    "conduct": "n.行为，举止；v.实施，进行；指挥",
    "confer": "v.授予；商议，讨论",
    "confess": "v.承认，坦白；忏悔",
    "confidence": "n.信心，信任；秘密(in confidence)",
    "confine": "v.限制，局限于(confine to)；n.界限(pl.)",
    "confirm": "v.确认，证实；批准",
    "conflict": "n.冲突，矛盾；v.冲突(conflict with)",
    "conform": "v.遵守，符合(conform to)；顺应",
    "confront": "v.面对，对抗；正视",
    "conscience": "n.良心，良知",
    "conscious": "adj.有意识的，清醒的；刻意的",
    "consecutive": "adj.连续的",
    "consent": "v./n.同意，允许",
    "consequence": "n.结果，后果；重要性",
    "conservative": "adj.保守的；n.保守派",
    "considerable": "adj.相当大的，值得考虑的",
    "considerate": "adj.体贴的，考虑周到的",
    "consist": "v.由…组成(consist of)；在于(consist in)",
    "consistent": "adj.一致的，始终如一的",
    "consolidate": "v.巩固，加强；合并",
    "conspicuous": "adj.显眼的，引人注目的",
    "constitute": "v.构成，组成；设立",
    "constrain": "v.限制，约束；强迫",
    "construct": "v.建造，构建；n.构想",
    "consult": "v.咨询，请教；查阅",
    "consume": "v.消费，消耗；耗尽(with)",
    "contact": "n./v.接触，联系",
    "contaminate": "v.污染，玷污",
    "contemplate": "v.沉思，仔细考虑；凝视",
    "contemporary": "adj.当代的；同时代的；n.同代人",
    "contempt": "n.蔑视，轻视",
    "contend": "v.竞争；声称，主张",
    "context": "n.背景，语境；上下文",
    "contract": "n.合同；v.收缩；感染 【熟词僻义：收缩/感染】",
    "contradict": "v.反驳；与…矛盾",
    "contrary": "n.相反(on the contrary)；adj.相反的",
    "contrast": "n./v.对比，对照(in contrast to)",
    "contribute": "v.贡献；捐献；投稿；促成(contribute to)",
    "controversial": "adj.有争议的",
    "controversy": "n.争论，争议",
    "convenience": "n.方便，便利",
    "convention": "n.惯例，常规；大会，会议",
    "conventional": "adj.传统的，惯例的",
    "converge": "v.汇集，聚集(converge on)",
    "converse": "v.交谈；adj.相反的",
    "convert": "v.转变，转换；使皈依",
    "convey": "v.传达，表达；运送",
    "convict": "v.定罪；n.罪犯",
    "conviction": "n.定罪；坚定信念",
    "convince": "v.使确信，说服(convince sb of)",
    "cooperate": "v.合作，协作",
    "coordinate": "v.协调；adj.同等的；n.坐标",
    "cope": "v.应对，处理(cope with)",
    "core": "n.核心，要点；果核；adj.核心的",
    "corporate": "adj.公司的，企业的；团体的",
    "correlate": "v.相互关联，相关(correlate with)",
    "correspond": "v.相符(correspond to)；通信(with)",
    "corrupt": "adj.腐败的；v.使腐败",
    "council": "n.委员会，理事会",
    "counsel": "n.忠告；辩护律师；v.建议",
    "counterpart": "n.对应的人/物，职位相当的人",
    "courtesy": "n.礼貌，彬彬有礼",
    "craft": "n.手艺，工艺；航天器；v.精心制作",
    "crash": "n./v.碰撞，坠毁；崩溃（金融/系统）",
    "credit": "n.信用；学分；赞扬(give credit to)；v.归功于",
    "criminal": "adj.犯罪的；n.罪犯",
    "crisis": "n.危机，紧要关头",
    "criterion": "n.标准，准则 (pl. criteria)",
    "critical": "adj.批评的；关键的；危急的",
    "crucial": "adj.至关重要的，决定性的",
    "crude": "adj.天然的，未加工的；粗鲁的",
    "cultivate": "v.培养；种植；建立（关系）",
    "curb": "v.控制，抑制；n.控制，勒马绳",
    "currency": "n.货币；流行，流通",
    "curriculum": "n.课程 (pl. curricula)",
    "cynical": "adj.愤世嫉俗的；怀疑人动机的",

    # ---- D ----
    "dazzle": "v.使目眩，使眼花；使赞叹不已",
    "deadline": "n.截止日期，最后期限",
    "deadly": "adj.致命的；极度的；adv.极其",
    "deaf": "adj.聋的；不愿听的(deaf to)",
    "debate": "n./v.辩论，争论",
    "debt": "n.债务，欠款(in debt)",
    "decade": "n.十年，十年期",
    "decay": "v./n.腐烂，腐朽；衰退",
    "deceive": "v.欺骗，蒙蔽",
    "decent": "adj.体面的，像样的；正派的",
    "decimal": "adj.十进制的；n.小数",
    "declaration": "n.宣言，声明；申报",
    "decline": "v./n.下降，衰退；婉拒",
    "decorate": "v.装饰，装潢；授予勋章",
    "decrease": "v./n.减少，降低",
    "dedicate": "v.致力于，献身于(dedicate to)；题献",
    "deduce": "v.推断，演绎(deduce from)",
    "deem": "v.认为，视为",
    "defect": "n.缺点，缺陷；v.背叛，叛逃",
    "defend": "v.防御，保卫；为…辩护",
    "deficiency": "n.缺乏，不足；缺陷",
    "define": "v.定义，界定；明确",
    "definite": "adj.明确的，确定的",
    "defy": "v.违抗，蔑视；使不可能，使落空",
    "degenerate": "v.退化，衰退；adj.堕落的",
    "delegate": "n.代表；v.委派，授权",
    "deliberate": "adj.故意的；深思熟虑的；v.仔细考虑",
    "delicate": "adj.精致的；微妙的；脆弱的",
    "deliver": "v.递送；发表（演讲）；接生",
    "democracy": "n.民主，民主制度",
    "demonstrate": "v.证明；示范；游行示威",
    "denial": "n.否认；拒绝给予",
    "denote": "v.表示，意味着",
    "denounce": "v.谴责，指责",
    "dense": "adj.密集的；浓密的；愚钝的",
    "dental": "adj.牙齿的，牙科的",
    "deny": "v.否认，否定；拒绝给予",
    "depart": "v.离开，出发；偏离",
    "depict": "v.描绘，描述",
    "deposit": "n.存款；押金；沉淀物；v.存放",
    "depress": "v.使沮丧；使萧条；按下",
    "deprive": "v.剥夺，使丧失(deprive sb of)",
    "derive": "v.源于(derive from)；获得",
    "descend": "v.下降；遗传(descend from)",
    "deserve": "v.值得，应得",
    "designate": "v.指定，指派；标明",
    "desirable": "adj.理想的，值得拥有的",
    "desperate": "adj.绝望的；孤注一掷的；极度渴望的",
    "despise": "v.鄙视，蔑视",
    "despite": "prep.尽管，不顾",
    "destination": "n.目的地，终点",
    "destiny": "n.命运，天命",
    "destruction": "n.破坏，毁灭",
    "detach": "v.拆卸，使分离；派遣",
    "detain": "v.拘留，扣押；耽搁",
    "detect": "v.发现，察觉；探测",
    "deteriorate": "v.恶化，变坏，退化",
    "determine": "v.决定，确定；使下定决心",
    "device": "n.装置，设备；策略",
    "devote": "v.致力于，奉献(devote to)",
    "diagnose": "v.诊断，判断",
    "dictate": "v.口述；命令，支配；n.命令(pl.)",
    "differentiate": "v.区分，区别；使不同",
    "diffuse": "v.扩散，传播；adj.弥漫的，冗长的",
    "digest": "v.消化；理解，领悟；n.摘要",
    "digital": "adj.数字的，数码的",
    "dignity": "n.尊严，高贵；庄严",
    "dilemma": "n.困境，进退两难",
    "diligent": "adj.勤奋的，勤勉的",
    "dilute": "v.稀释，冲淡；adj.稀释的",
    "dimension": "n.维度，尺寸；(pl.)规模",
    "diminish": "v.（使）减少，缩小；贬低",
    "diploma": "n.毕业文凭，学位证书",
    "diplomatic": "adj.外交的；有策略的，圆滑的",
    "disable": "v.使丧失能力，使残疾",
    "disaster": "n.灾难，不幸",
    "discard": "v.丢弃，抛弃 【易混：discard vs abandon】",
    "discharge": "v./n.释放；解雇；履行职责 【熟词僻义：履行职责】",
    "discipline": "n.纪律；学科；v.训练，惩罚",
    "disclose": "v.揭露，透露",
    "discount": "n.折扣；v.不重视，忽视 【熟词僻义：不重视】",
    "discourse": "n.话语，论述；v.讲述",
    "discreet": "adj.谨慎的，慎重的",
    "discrepancy": "n.差异，不一致",
    "discriminate": "v.区别；歧视(discriminate against)",
    "disgrace": "n.耻辱，丢脸；v.使蒙羞",
    "disguise": "v./n.伪装，假扮",
    "disgust": "n.厌恶，恶心；v.使厌恶",
    "dismay": "n.沮丧，惊慌；v.使沮丧",
    "dismiss": "v.解雇；不予理会；驳回",
    "disorder": "n.混乱，无序；失调",
    "dispatch": "v./n.派遣，发送",
    "disperse": "v.（使）分散，驱散",
    "displace": "v.取代，替代；使流离失所",
    "display": "v./n.展示，陈列；显示",
    "disposal": "n.处置，处理(at one's disposal)",
    "dispose": "v.处理，处置(dispose of)；使倾向于",
    "dispute": "n./v.争论，争端",
    "disregard": "v./n.忽视，不理会",
    "disrupt": "v.扰乱，使中断",
    "dissolve": "v.(使)溶解；解散；消除",
    "distinct": "adj.明显的；独特的，截然不同的",
    "distinguish": "v.区分，辨别(distinguish from)",
    "distort": "v.扭曲，歪曲；使变形",
    "distract": "v.分散注意力，使分心",
    "distribute": "v.分配，分发；分布",
    "diverse": "adj.多种多样的，不同的",
    "divert": "v.使转向，转移；使娱乐",
    "dividend": "n.股息，红利；被除数",
    "divine": "adj.神圣的，天赐的；极好的",
    "divorce": "n./v.离婚；分离，脱离",
    "document": "n.文件，文献；v.记录，记载",
    "domain": "n.（知识/活动）领域；域名；领地",
    "domestic": "adj.国内的；家庭的；驯养的",
    "dominant": "adj.占优势的，支配的；显性的",
    "dominate": "v.支配，控制；占首要地位",
    "donate": "v.捐赠，捐献",
    "doom": "n.厄运，劫数；v.注定(be doomed to)",
    "draft": "n.草稿；汇票；v.起草；征召",
    "drain": "v.排空；耗尽；n.下水道，(人才)流失(brain drain)",
    "drama": "n.戏剧；戏剧性事件",
    "drastic": "adj.激烈的，猛烈的；严厉的",
    "dread": "v./n.恐惧，害怕",
    "drift": "v./n.漂流；n.趋势，大意",
    "drought": "n.干旱",
    "dubious": "adj.可疑的；半信半疑的",
    "duplicate": "n.复制品；v.复制；adj.复制的",
    "durable": "adj.耐用的，持久的",
    "dwell": "v.居住；详述(dwell on 老是想着/唠叨)",
    "dynamic": "adj.动态的；有活力的；n.动力(pl.)",

    # ---- E ----
    "earnest": "adj.认真的，诚挚的",
    "ease": "n.容易；舒适；v.减轻，缓和",
    "echo": "v.回响，附和；n.回声",
    "eclipse": "n.日食，月食；黯然失色；v.使失色",
    "ecology": "n.生态学，生态",
    "economic": "adj.经济的，经济学的；有利可图的",
    "economical": "adj.节约的，经济的 【易混：economic经济的】",
    "edible": "adj.可食用的",
    "edit": "v.编辑，剪辑；主编",
    "effective": "adj.有效的；实际的",
    "efficiency": "n.效率，效能",
    "elaborate": "adj.精心制作的；v.详细阐述",
    "elapse": "v.（时间）流逝",
    "elastic": "adj.有弹性的；灵活的",
    "elegant": "adj.优雅的，精美的",
    "element": "n.元素；要素；成分",
    "elevate": "v.提高，提升；使高尚",
    "eligible": "adj.有资格的，符合条件的",
    "eliminate": "v.消除，淘汰",
    "elite": "n.精英，上层人士；adj.精锐的",
    "eloquent": "adj.雄辩的，有口才的",
    "embark": "v.上船/飞机；开始(embark on/upon)",
    "embarrass": "v.使尴尬，使难堪",
    "embed": "v.嵌入，植入；使深留脑中",
    "embody": "v.体现，代表；收录",
    "embrace": "v.拥抱；包含；欣然接受",
    "emerge": "v.出现，浮现；暴露",
    "emit": "v.发出，散发（光/热/声音）",
    "emotion": "n.情感，情绪",
    "emphasis": "n.强调，重点(put emphasis on)",
    "empirical": "adj.经验主义的，以实验为依据的",
    "enable": "v.使能够，使可能",
    "enclose": "v.围住；附入（信封）",
    "encounter": "v./n.遭遇，碰到",
    "endeavor": "n./v.努力，尽力",
    "endow": "v.赋予，捐赠(be endowed with 天生具有)",
    "endure": "v.忍受，忍耐；持久",
    "enforce": "v.强制执行；加强",
    "engage": "v.吸引；雇用；从事(engage in)；订婚",
    "enhance": "v.提高，增强，改善",
    "enlighten": "v.启发，启迪，开导",
    "enormous": "adj.巨大的，庞大的",
    "enrich": "v.使丰富，充实；使富裕",
    "enroll": "v.注册，登记，入学",
    "ensure": "v.确保，保证",
    "entail": "v.需要，必然导致(entail that)",
    "enterprise": "n.企业；事业心，进取心",
    "entertain": "v.使娱乐；招待，款待；怀有（想法/希望）",
    "enthusiasm": "n.热情，热忱",
    "entitle": "v.给…权利(entitle sb to)；给…命名",
    "entity": "n.实体，独立存在体",
    "entrepreneur": "n.企业家，创业者",
    "envisage": "v.设想，展望",
    "epidemic": "n.流行病，传染病；adj.流行的",
    "equip": "v.装备，配备(equip with)",
    "equivalent": "adj.等价的，同等的；n.等价物",
    "era": "n.时代，纪元",
    "erect": "v.建立，竖立；adj.直立的",
    "erode": "v.侵蚀，腐蚀；逐渐损害",
    "erupt": "v.（火山）喷发；（战争/冲突）爆发",
    "escalate": "v.逐步升级，加剧",
    "essay": "n.短文，文章；v.试图",
    "essence": "n.本质，实质；精华(in essence)",
    "essential": "adj.必要的，本质的；n.要素(pl.)",
    "establish": "v.建立，设立；确立，证实",
    "estate": "n.房地产；庄园；遗产(real estate 房地产)",
    "esteem": "n./v.尊重，尊敬",
    "estimate": "v./n.估计，估算",
    "eternal": "adj.永恒的，永久的",
    "evade": "v.逃避，回避；规避",
    "evaluate": "v.评估，评价",
    "evaporate": "v.蒸发；消失",
    "evidence": "n.证据，根据；v.证明",
    "evident": "adj.明显的，明白的",
    "evil": "adj.邪恶的；n.罪恶，坏事",
    "evoke": "v.唤起，引起（记忆/情感）",
    "evolution": "n.进化，演变；发展",
    "evolve": "v.进化，逐步发展",
    "exacerbate": "v.加剧，使恶化",
    "exceed": "v.超过，超越",
    "excel": "v.擅长，突出(excel at/in)",
    "excess": "n.过量，无节制；adj.过量的",
    "exclude": "v.排除，排斥",
    "exclusive": "adj.独有的，排外的；n.独家新闻",
    "execute": "v.执行，实施；处死",
    "exemplify": "v.举例说明，作为…的典范",
    "exert": "v.运用，施加（影响/压力）(exert oneself 努力)",
    "exhaust": "v.使筋疲力尽；耗尽；n.尾气",
    "exhibit": "v.展示；n.展览品",
    "exile": "n./v.流放，放逐",
    "expand": "v.扩大，扩展；膨胀",
    "expel": "v.驱逐，开除；排出",
    "expend": "v.花费，耗费(expend on)",
    "expense": "n.费用，开支(at the expense of 以…为代价)",
    "expertise": "n.专长，专门知识",
    "expire": "v.到期，失效；逝世",
    "explicit": "adj.明确的，清楚的",
    "exploit": "v.开发，利用；剥削",
    "explore": "v.探索，勘探；探讨",
    "explosive": "adj.爆炸的；易爆的；n.炸药",
    "export": "v./n.出口，输出",
    "expose": "v.暴露，揭露；使接触(expose to)",
    "exquisite": "adj.精美的，精致的；敏锐的",
    "extend": "v.延伸，延长；扩大；给予",
    "extensive": "adj.广泛的，大量的",
    "extent": "n.程度，范围(to some extent 在某种程度上)",
    "external": "adj.外部的，外来的",
    "extinct": "adj.灭绝的；消亡的",
    "extinguish": "v.熄灭（火）；消灭",
    "extract": "v.提取，提炼；n.摘录",
    "extraordinary": "adj.非凡的，特别的",
    "extravagant": "adj.奢侈的，浪费的；过分的",
    "extreme": "adj.极端的；n.极端",

    # ---- F ----
    "fabricate": "v.捏造；制造，装配",
    "facilitate": "v.促进，使便利",
    "facility": "n.设施，设备；天资，才能(with)",
    "faculty": "n.能力，官能；全体教职员",
    "fade": "v.褪色，枯萎；逐渐消失",
    "faithful": "adj.忠实的，忠诚的；如实的",
    "fake": "adj.假的；n.假货；v.伪造，假装",
    "famine": "n.饥荒",
    "fancy": "v.想象，喜爱；adj.花哨的；n.想象力",
    "fantastic": "adj.极好的；奇异的；异想天开的",
    "fascinate": "v.使着迷，强烈吸引",
    "fashion": "n.时尚；方式(in a ... fashion 以...方式)",
    "fatal": "adj.致命的，灾难性的",
    "fate": "n.命运，天命",
    "fatigue": "n./v.疲劳，疲惫",
    "feasible": "adj.可行的，行得通的",
    "feature": "n.特征，特点；v.以…为特色",
    "federal": "adj.联邦的，联邦政府的",
    "feeble": "adj.虚弱的，无力的",
    "feedback": "n.反馈，反馈意见",
    "feminine": "adj.女性的，阴性的",
    "fertilizer": "n.肥料",
    "fiction": "n.小说；虚构的事",
    "fierce": "adj.凶猛的；激烈的",
    "finance": "n.财政，金融；v.资助",
    "finite": "adj.有限的，限定的",
    "flaw": "n.缺陷，瑕疵；v.使有缺陷",
    "flexible": "adj.灵活的；有弹性的",
    "flock": "n.羊群，(鸟的)群；v.聚集，蜂拥而至",
    "flourish": "v.繁荣，兴旺；挥舞",
    "fluctuate": "v.波动，涨落",
    "flush": "v.冲洗；脸红；adj.齐平的；富有的",
    "forecast": "v./n.预测，预报",
    "foremost": "adj.最重要的(first and foremost)",
    "forge": "v.锻造；伪造；稳步前进(forge ahead)",
    "formidable": "adj.可怕的；令人敬畏的；难对付的",
    "formula": "n.公式，方程式；方案",
    "formulate": "v.制定，规划；确切表达",
    "forthcoming": "adj.即将到来的；乐于提供信息的",
    "foster": "v.培养，促进；寄养，收养",
    "foundation": "n.基础；基金会；创建",
    "fraction": "n.小部分，片段；分数",
    "fragile": "adj.脆弱的；易碎的",
    "fragment": "n.碎片，片段；v.使破碎",
    "framework": "n.框架，结构；体系",
    "frank": "adj.坦白的，直率的",
    "fraud": "n.欺诈，诈骗；骗子",
    "friction": "n.摩擦；分歧",
    "frontier": "n.边境，边界；前沿",
    "fruitful": "adj.富有成果的，多产的",
    "frustrate": "v.使沮丧，使受挫；阻止",
    "fulfill": "v.实现，完成；满足",
    "function": "n.功能，作用；v.运行，起作用",
    "fundamental": "adj.基础的，根本的",
    "furnish": "v.提供；为…配备家具",
    "furthermore": "adv.此外，而且",
    "fury": "n.狂怒，暴怒",
    "fuse": "v.熔化，融合；n.保险丝，导火线",
    "futile": "adj.徒劳的，无效的",

    # ---- G ----
    "gauge": "n.测量仪表；标准；v.估计，判定",
    "generalize": "v.概括，归纳；推广",
    "generate": "v.产生，创造",
    "generous": "adj.慷慨的，大方的；宽厚的",
    "genetic": "adj.基因的，遗传的",
    "genius": "n.天才，天赋",
    "genuine": "adj.真正的，真诚的",
    "gesture": "n.手势，姿势；姿态",
    "glamour": "n.魅力，吸引力",
    "glimpse": "n./v.一瞥，瞥见(catch a glimpse of)",
    "glitter": "v./n.闪耀，闪烁",
    "global": "adj.全球的；全面的",
    "gloomy": "adj.昏暗的；沮丧的；前景黯淡的",
    "glorious": "adj.光荣的，辉煌的",
    "grace": "n.优雅，恩典；v.为增色",
    "gracious": "adj.亲切的，和蔼的；雅致的",
    "gradual": "adj.逐渐的，逐步的",
    "grant": "v.授予，准予；承认(take for granted 想当然)；n.拨款",
    "graphic": "adj.形象的，图解的；生动的",
    "grasp": "v./n.抓住；理解，掌握",
    "grateful": "adj.感激的",
    "grave": "adj.严重的；严肃的；n.坟墓",
    "gravity": "n.重力；严重性；严肃",
    "grieve": "v.使悲伤，使伤心(grieve for/over)",
    "grind": "v.磨碎，碾碎；n.苦差事",
    "grip": "v./n.紧握；吸引住；控制力",
    "gross": "adj.总的，毛的(gross income 总收入)；严重的；令人恶心的",
    "guarantee": "n.保证，担保；v.保证",
    "guardian": "n.监护人，保护人",
    "guideline": "n.指导方针，准则",
    "guilty": "adj.有罪的；内疚的",
    "gulf": "n.海湾；巨大分歧",

    # ---- H ----
    "habitat": "n.栖息地，生存环境",
    "halt": "v./n.停止，中断",
    "hamper": "v.妨碍，阻碍，束缚",
    "handicap": "n.障碍，缺陷；v.妨碍",
    "handle": "v.处理，应对；操作；n.把手",
    "hardship": "n.艰难，困苦",
    "harmony": "n.和谐，融洽(in harmony with)",
    "harness": "v.利用（自然资源）；给…上挽具",
    "harsh": "adj.严酷的；刺耳的",
    "haste": "n.匆忙，仓促(in haste)",
    "hatred": "n.憎恨，仇恨",
    "hazard": "n.危险，危害；v.冒险",
    "heal": "v.治愈，康复；弥合（分歧）",
    "heap": "n.堆(a heap of)；大量(heaps of)；v.堆积",
    "heighten": "v.(使)提高，加强",
    "hemisphere": "n.半球 (northern/southern hemisphere)",
    "hence": "adv.因此，所以；从现在开始",
    "heritage": "n.遗产，传统",
    "hierarchy": "n.等级制度，层级",
    "highlight": "v.强调，突出；n.最重要的部分",
    "hinder": "v.阻碍，妨碍(hinder from)",
    "hitherto": "adv.迄今，到目前为止",
    "hoist": "v.吊起，升起，举起",
    "horizon": "n.地平线；(pl.)眼界(on the horizon 即将发生)",
    "hospitality": "n.好客，殷勤招待",
    "hostile": "adj.敌对的，敌意的；不利的",
    "household": "n.家庭，户；adj.家喻户晓的",
    "humanity": "n.人类；人性；人文学科",
    "humble": "adj.谦虚的；卑微的；v.使谦卑",
    "hypothesis": "n.假说，假设",
    "hysterical": "adj.歇斯底里的，情绪失控的",

    # ---- I ----
    "ideal": "adj.理想的；n.理想",
    "identical": "adj.完全相同的，一模一样的",
    "identify": "v.识别，确认；认同(identify with)",
    "ideology": "n.意识形态，思想体系",
    "ignorance": "n.无知，愚昧",
    "ignorant": "adj.无知的；不知道的(be ignorant of)",
    "ignore": "v.忽视，不理会",
    "illiterate": "adj.文盲的；外行的",
    "illuminate": "v.照明；阐明，启发",
    "illustrate": "v.（举例）说明，阐明；加插图",
    "imaginary": "adj.想象中的，虚构的",
    "imaginative": "adj.富有想象力的",
    "imitate": "v.模仿，仿效",
    "immense": "adj.巨大的，无边的",
    "immerse": "v.使沉浸，使专心于(immerse in)",
    "immune": "adj.免疫的；不受影响的(immune to)",
    "impact": "n./v.影响，冲击(have impact on)",
    "impair": "v.损害，削弱",
    "impartial": "adj.公正的，不偏袒的",
    "imperative": "adj.至关重要的；命令式的",
    "implement": "v.实施，执行；n.工具",
    "implication": "n.含义，暗示；可能的影响",
    "implicit": "adj.含蓄的，不直接言明的 【反义词：explicit明确的】",
    "imply": "v.暗示，暗指；意味着",
    "impose": "v.强加(impose on)；征税；施加影响",
    "impress": "v.给…留下深刻印象(impress sb with)",
    "impulse": "n.冲动，一时的念头(on impulse 一时冲动)",
    "incentive": "n.激励，奖励；动机",
    "incidence": "n.发生率，发病率",
    "incline": "v.(使)倾向于；n.斜坡",
    "incorporate": "v.包含，合并，纳入",
    "incredible": "adj.难以置信的",
    "incur": "v.招致，引起（费用/风险/损失）",
    "independence": "n.独立，自主",
    "index": "n.指数；索引；v.编索引",
    "indicate": "v.表明，指示；暗示",
    "indifferent": "adj.漠不关心的，冷淡的(be indifferent to)",
    "indignant": "adj.愤怒的，愤慨的",
    "indispensable": "adj.不可或缺的，必需的",
    "induce": "v.引起，导致；劝说，引诱",
    "indulge": "v.沉溺于(indulge in)；纵容",
    "industrialize": "v.(使)工业化",
    "inevitable": "adj.不可避免的，必然发生的",
    "infant": "n.婴儿；adj.初期的",
    "infer": "v.推断，推论(infer from)",
    "inferior": "adj.低劣的(inferior to)；n.下级",
    "inflation": "n.通货膨胀；膨胀",
    "inflict": "v.使遭受（痛苦/打击）(inflict on)",
    "influence": "n./v.影响，作用",
    "influential": "adj.有影响力的",
    "inform": "v.通知(inform sb of)；对…有影响",
    "ingenious": "adj.巧妙的，有独创性的",
    "ingredient": "n.成分，原料；要素",
    "inhabit": "v.居住于",
    "inherent": "adj.固有的，内在的(inherent in)",
    "inhibit": "v.抑制，阻止(inhibit from)",
    "initial": "adj.最初的；n.首字母",
    "initiate": "v.开始，发起；使初步了解(into)",
    "initiative": "n.主动性(take the initiative)；倡议",
    "inject": "v.注射，注入(inject into)",
    "innovation": "n.创新，革新",
    "innumerable": "adj.无数的，数不清的",
    "inquire": "v.询问，打听(inquire into 调查)",
    "insight": "n.洞察力，深刻见解(insight into)",
    "inspect": "v.检查，视察",
    "inspire": "v.激励，鼓舞；赋予灵感",
    "installment": "n.分期付款的一部；一集（连载）",
    "instinct": "n.本能，直觉",
    "institute": "n.学院，研究院；v.建立，制定",
    "instrument": "n.仪器；乐器；工具，手段",
    "insulate": "v.使绝缘；隔离",
    "insult": "v./n.侮辱，羞辱",
    "integrate": "v.(使)融合，整合(integrate into/with)",
    "integrity": "n.正直，诚实；完整 【熟词僻义：完整】",
    "intellectual": "adj.智力的；n.知识分子",
    "intelligence": "n.智力；情报",
    "intense": "adj.强烈的，剧烈的；紧张的",
    "intensive": "adj.密集的，强化的；精耕细作的",
    "intent": "n.意图；adj.专心的(intent on 专心于)",
    "interact": "v.互动，相互作用(interact with)",
    "interfere": "v.干涉，干预(interfere in/with)",
    "interior": "adj.内部的；n.内部",
    "intermediate": "adj.中间的，中级的",
    "intermittent": "adj.间歇的，断断续续的",
    "internal": "adj.内部的，内在的；国内的",
    "interpret": "v.解释；口译；理解",
    "interval": "n.间隔(at intervals 每隔一段时间)",
    "intervene": "v.干预，介入(intervene in)",
    "intimate": "adj.亲密的；私人的；v.暗示",
    "intricate": "adj.复杂的，错综的",
    "intuition": "n.直觉",
    "invade": "v.入侵，侵略；涌入",
    "invalid": "adj.无效的；n.病人",
    "invariably": "adv.总是，不变地",
    "invert": "v.使倒转，使颠倒",
    "invest": "v.投资(invest in)；投入；授予",
    "investigate": "v.调查，研究",
    "invoke": "v.援引（法律/理论）；唤起",
    "involve": "v.涉及，包含；使卷入(be involved in)",
    "irony": "n.反讽，讽刺",
    "irritate": "v.激怒，使烦躁；刺激",
    "isolate": "v.隔离，孤立(isolate from)",
    "issue": "n.问题；期号；v.发布，发行",
    "item": "n.项目，条款；一件物品",

    # ---- J ----
    "jealous": "adj.嫉妒的；小心守护的(jealous of)",
    "joint": "adj.共同的，联合的；n.关节，接合处",
    "journal": "n.期刊，杂志；日记",
    "judgment": "n.判断力；判决；看法",
    "junction": "n.交叉路口，枢纽站；汇合处",
    "justify": "v.证明…是正当的，为…辩护",
    "juvenile": "adj.青少年的；幼稚的；n.青少年",

    # ---- K ----
    "keen": "adj.热心的(keen on)；敏锐的；激烈的",
    "kidnap": "v.绑架，劫持",
    "kindergarten": "n.幼儿园",
    "knit": "v.编织；紧密结合(knit together)",
    "knot": "n.结；(问题的)症结所在；v.系紧",

    # ---- L ----
    "label": "n.标签；v.贴标签，把…归类",
    "lag": "v.落后(lag behind)；n.滞后",
    "landscape": "n.风景，景观；形势",
    "lapse": "n.失误；流逝；v.失效",
    "latent": "adj.潜在的，潜伏的",
    "latter": "n.后者(the former...the latter...)",
    "launch": "v.发射；发起，推出；n.上市，发行",
    "layer": "n.层，层次",
    "layout": "n.布局，安排",
    "leak": "v./n.泄漏，漏出；透露",
    "lean": "v.倾斜；倚靠；adj.瘦的；精简的",
    "leap": "v./n.跳跃，飞跃(leap forward 跃进)",
    "lease": "n.租约；v.出租，租借",
    "legacy": "n.遗产，遗留问题",
    "legend": "n.传说，传奇人物",
    "legislation": "n.法律，法规；立法",
    "legitimate": "adj.合法的，正当的",
    "leisure": "n.闲暇，空闲(at leisure 从容地)",
    "liable": "adj.有义务的(liable for)；可能(liable to)",
    "liberal": "adj.自由的；开明的；慷慨的",
    "likelihood": "n.可能性(in all likelihood 很可能)",
    "likewise": "adv.同样地，类似地",
    "limitation": "n.限制，局限",
    "linger": "v.徘徊，逗留；持续留存",
    "literacy": "n.读写能力，有文化",
    "literally": "adv.按字面意思；确实，简直",
    "literary": "adj.文学的；书面的",
    "litter": "n.垃圾；一窝幼崽；v.乱扔",
    "lobby": "n.大厅；游说团体；v.游说",
    "logical": "adj.合乎逻辑的",
    "loom": "v.隐约出现(loom large)；(危机)逼近",
    "lounge": "n.休息室；v.懒散地靠",
    "loyal": "adj.忠诚的，忠心的(loyal to)",
    "lump": "n.块，肿块；v.把…归拢(lump together)",
    "luxury": "n.奢侈，奢侈品",

    # ---- M ----
    "magnificent": "adj.壮丽的，宏伟的",
    "magnify": "v.放大，扩大；夸大",
    "magnitude": "n.大小，重要性；震级",
    "maintain": "v.保持，维持；维修；坚持认为",
    "manifest": "v.表明，表现；adj.明显的 【熟词僻义：manifest v. 表明】",
    "manipulate": "v.操纵，控制；操作",
    "manual": "adj.手工的，体力的；n.手册",
    "manufacture": "v.制造，生产；n.制造品",
    "manuscript": "n.手稿，原稿",
    "margin": "n.边缘；利润，差额；余地(by a narrow margin)",
    "marital": "adj.婚姻的",
    "massive": "adj.大量的；巨大的",
    "masterpiece": "n.杰作，名著",
    "mate": "n.伙伴，配偶；v.交配",
    "mature": "adj.成熟的；v.成熟",
    "maximize": "v.最大化，充分利用",
    "mechanism": "n.机制，原理；机械装置",
    "media": "n.媒体，媒介",
    "mediate": "v.调解，居中斡旋(mediate between)",
    "medieval": "adj.中世纪的，中古的",
    "membership": "n.会员资格，成员身份",
    "memorial": "n.纪念碑；adj.纪念的",
    "menace": "n./v.威胁，恐吓",
    "mental": "adj.精神的，心理的；智力的",
    "mercy": "n.仁慈，宽容(at the mercy of 受…支配)",
    "merge": "v.合并，融合(merge into/with)",
    "merit": "n.优点，价值；v.值得",
    "metropolitan": "adj.大都市的",
    "migrate": "v.迁移，移居；(鸟类)迁徙",
    "mild": "adj.温和的；轻微的；淡味的",
    "military": "adj.军事的，军用的",
    "mingle": "v.混合，交织；交际(mingle with)",
    "miniature": "n.缩微模型；adj.微型的",
    "minimize": "v.最小化；贬低，轻视",
    "minor": "adj.较小的；n.未成年人",
    "miracle": "n.奇迹，不可思议的事",
    "miserable": "adj.痛苦的；悲惨的",
    "misfortune": "n.不幸，厄运",
    "mislead": "v.误导，使误信",
    "mission": "n.使命，任务；使团",
    "mobilize": "v.动员，调动",
    "moderate": "adj.适度的；温和的；v.缓和",
    "modest": "adj.谦虚的；适度的；朴素的",
    "modify": "v.修改，更改；修饰",
    "monitor": "n.监视器；班长；v.监控",
    "monopoly": "n.垄断，独占",
    "monotonous": "adj.单调的，乏味的",
    "monument": "n.纪念碑；历史遗迹",
    "morality": "n.道德，道德观",
    "mortal": "adj.致命的；凡人的",
    "motion": "n.运动；动作；提议；v.示意",
    "motivate": "v.激励，激发；是…的动机",
    "mount": "v.登上；增加，上升；镶嵌；组织",
    "multiple": "adj.多重的，多种多样的；n.倍数",
    "multiply": "v.乘；倍增；繁殖",
    "mutual": "adj.相互的；共同的",
    "mysterious": "adj.神秘的，难以理解的",
    "myth": "n.神话；错误观念",

    # ---- N ----
    "narrative": "n.叙述，故事；adj.叙述的",
    "nasty": "adj.令人不快的；下流的",
    "necessity": "n.必要性；必需品(of necessity 必然地)",
    "neglect": "v./n.忽视，疏忽",
    "negligible": "adj.可忽略不计的",
    "negotiate": "v.谈判，协商(negotiate with)",
    "neutral": "adj.中立的；中性的",
    "nominal": "adj.名义上的；微不足道的",
    "nominate": "v.提名；任命",
    "nonetheless": "adv.尽管如此，然而",
    "norm": "n.标准，规范；常态",
    "notable": "adj.值得注意的，显著的",
    "notify": "v.通知，告知(notify sb of)",
    "notion": "n.概念，观念；看法",
    "notorious": "adj.臭名昭著的(notorious for)",
    "nourish": "v.滋养，养育；怀有（希望等）",
    "novelty": "n.新奇，新颖；新奇的事物",
    "nuclear": "adj.核能的；核心的",
    "numerical": "adj.数字的，用数字表示的",
    "nurture": "v./n.培养，养育",

    # ---- O ----
    "obedient": "adj.服从的，顺从的",
    "objection": "n.反对，异议(objection to)",
    "objective": "n.目标；adj.客观的",
    "obligation": "n.义务，责任",
    "oblige": "v.迫使(be obliged to)；帮忙(oblige sb)",
    "obscure": "adj.晦涩的；无名的；v.使模糊",
    "observation": "n.观察；评论",
    "obsess": "v.使着迷，使痴迷；唠叨",
    "obsolete": "adj.过时的，废弃的",
    "obstacle": "n.障碍，阻碍(obstacle to)",
    "obtain": "v.获得，得到",
    "occasion": "n.场合，时机；理由(on occasion 偶尔)",
    "occupy": "v.占用；使忙碌(occupy oneself with)；占领",
    "occur": "v.发生；出现(occur to sb 想到)",
    "odds": "n.可能性，机会(at odds 有分歧/矛盾)",
    "offend": "v.冒犯，得罪；违背",
    "offensive": "adj.冒犯的；进攻性的；n.进攻",
    "offset": "v.抵消，补偿；n.抵消物",
    "omission": "n.遗漏，疏忽",
    "onset": "n.开始，发作",
    "opaque": "adj.不透明的；晦涩的",
    "operative": "adj.有效的，起作用的",
    "opponent": "n.对手，反对者",
    "oppress": "v.压迫，压抑；使烦恼",
    "optimal": "adj.最优的，最理想的",
    "optimistic": "adj.乐观的(optimistic about)",
    "option": "n.选择，选项",
    "orbit": "n.轨道；v.绕轨道运行",
    "organic": "adj.有机的；器官的；逐步发展的",
    "orient": "v.使适应，定位(orient to)；n.东方",
    "original": "adj.原来的；独创的；n.原稿",
    "originate": "v.起源(originate from/in)；创造",
    "ornament": "n.装饰品；v.装饰",
    "orthodox": "adj.正统的，传统的",
    "outbreak": "n.(战争/疾病的)爆发",
    "outcome": "n.结果，后果",
    "outline": "n.大纲；轮廓；v.概述",
    "outlook": "n.观点，看法；前景",
    "output": "n.产出，产量；输出",
    "outrage": "n./v.愤怒，暴行；使震怒",
    "outset": "n.开始，开端(at/from the outset)",
    "overcome": "v.克服，战胜",
    "overlap": "v./n.重叠，部分相同",
    "overlook": "v.俯瞰；忽视；宽恕 【熟词僻义：忽视】",
    "overt": "adj.公开的，明显的",
    "overtake": "v.超过，赶上",
    "overthrow": "v./n.推翻，打倒",
    "overwhelm": "v.使不知所措；压倒，淹没",
    "ownership": "n.所有权",

    # ---- P ----
    "pace": "n.步伐，速度(keep pace with 跟上)",
    "package": "n.包裹；一揽子方案；v.包装",
    "panel": "n.专家组；面板；控制板",
    "panic": "n.恐慌；v.(使)恐慌",
    "paradox": "n.悖论，矛盾的说法",
    "parallel": "adj.平行的；同时发生的；n.相似物",
    "paralyze": "v.使瘫痪；使丧失作用",
    "parcel": "n.包裹；v.分配",
    "partial": "adj.部分的；偏袒的(partial to)",
    "participant": "n.参与者，参加者",
    "participate": "v.参加(participate in)",
    "passion": "n.热情，激情；酷爱",
    "passive": "adj.被动的，消极的",
    "patent": "n.专利；adj.专利的；v.取得专利",
    "pathetic": "adj.可怜的，悲哀的",
    "patriotic": "adj.爱国的",
    "patrol": "v./n.巡逻，巡查",
    "patron": "n.赞助人，资助者；老主顾",
    "pave": "v.铺路(pave the way for 为…铺平道路)",
    "peak": "n.山峰，顶峰；v.达到高峰",
    "peculiar": "adj.奇怪的；独有的(peculiar to)",
    "penalty": "n.惩罚，罚款；不利后果",
    "penetrate": "v.渗透，进入；洞察",
    "perceive": "v.察觉，感知；理解",
    "perpetual": "adj.永久的，持续的",
    "perplex": "v.使困惑，使费解",
    "persist": "v.坚持(persist in)；继续存在",
    "perspective": "n.观点，视角；远景",
    "pessimistic": "adj.悲观的(pessimistic about)",
    "phenomenon": "n.现象 (pl. phenomena)",
    "philosophy": "n.哲学；人生哲学",
    "pinpoint": "v.精确定位；n.极小点",
    "plague": "n.瘟疫；v.困扰",
    "plead": "v.恳求；为…辩护(plead for)",
    "pledge": "n./v.保证，誓言",
    "plunge": "v./n.猛跌，骤降(plunge into 投入)",
    "poison": "n.毒药；v.毒害",
    "polish": "v.擦亮；润色；n.上光剂",
    "poll": "n.民意调查，投票",
    "pool": "n.水池；共用的资源/人才；v.集中（资源）",
    "portion": "n.一部分，一份",
    "portrait": "n.肖像，画像；描述",
    "portray": "v.描绘，刻画；扮演",
    "pose": "v.造成（威胁/问题）；摆姿势；假装",
    "positive": "adj.积极的；肯定的；阳性的",
    "possess": "v.拥有，具备",
    "potential": "adj.潜在的；n.潜力",
    "poverty": "n.贫穷，贫困",
    "precaution": "n.预防措施(take precautions)",
    "precede": "v.先于，在…之前发生",
    "precedent": "n.先例，前例",
    "precise": "adj.精确的，准确的",
    "predator": "n.捕食性动物；掠夺者",
    "predominant": "adj.占主导地位的",
    "prejudice": "n.偏见；v.使有偏见(prejudice against)",
    "preliminary": "adj.初步的，预备的",
    "premise": "n.前提(on the premise that 以…为前提)",
    "premium": "n.保险费；附加费；adj.高端的",
    "prescribe": "v.开药方；规定(prescribe for)",
    "preserve": "v.保存，保护；维持",
    "preside": "v.主持(preside over/at)",
    "prestige": "n.威望，声望",
    "presume": "v.假定，推测",
    "prevail": "v.盛行(prevail over/against)；占上风",
    "prey": "n.猎物(prey on 捕食/利用)",
    "primitive": "adj.原始的，简陋的",
    "principal": "adj.主要的，最重要的；n.校长；本金",
    "principle": "n.原则，原理(in principle 原则上)",
    "prior": "adj.优先的，在前的(prior to 在…之前)",
    "priority": "n.优先权，重点(give priority to)",
    "privilege": "n.特权，荣幸",
    "probe": "v./n.探查，探究，调查",
    "proceed": "v.继续，接着做(proceed with/to)",
    "proclaim": "v.宣告，公布",
    "profound": "adj.深刻的，深远的",
    "prohibit": "v.禁止(prohibit from)",
    "prolong": "v.延长，拖延",
    "prominent": "adj.杰出的；突出的，显眼的",
    "promising": "adj.有前途的，有希望的",
    "promote": "v.促进；提升；推销",
    "prompt": "v.促使，引起；adj.迅速的",
    "proof": "n.证据，证明；adj.防…的(-proof 后缀)",
    "proportion": "n.比例(in proportion to 与…成比例)",
    "proposal": "n.提议，建议；求婚",
    "propose": "v.提议；提出；求婚",
    "prospect": "n.前景，展望(prospect of/for)",
    "prosper": "v.繁荣，兴旺",
    "protest": "n./v.抗议，反对(protest against)",
    "provision": "n.供应；条款；准备(provision for)",
    "provoke": "v.激怒，挑衅；引起",
    "punctual": "adj.准时的，守时的",
    "purchase": "v./n.购买",
    "purify": "v.使净化，提纯",
    "pursue": "v.追求，致力于；追踪",
    "puzzle": "v.使困惑；n.谜题，难题",

    # ---- Q ----
    "qualification": "n.资格，资历；限定条件",
    "quantify": "v.量化，用数量表示",
    "quantity": "n.数量(in quantity 大量)",
    "quarter": "n.四分之一；一刻钟；区域(pl.)住处",
    "quest": "n.探索，追求(in quest of)",
    "quota": "n.配额，限额",

    # ---- R ----
    "radiant": "adj.光辉的；容光焕发的",
    "radical": "adj.根本的；激进的；n.激进分子",
    "random": "adj.随机的(at random 随机地)",
    "range": "n.范围，幅度；山脉；v.变动(range from...to)",
    "rank": "n.等级；v.排名，分等级",
    "rare": "adj.稀有的，罕见的",
    "ratio": "n.比率，比例(ratio of A to B)",
    "rational": "adj.理性的，合理的",
    "raw": "adj.生的；未加工的；原始的(raw material)",
    "realm": "n.领域，范围；王国",
    "rear": "adj.后面的；v.抚养；n.后方",
    "rebel": "n.叛逆者；v.反抗(rebel against)",
    "recall": "v./n.回忆；召回",
    "recession": "n.经济衰退",
    "reckon": "v.认为，估计(reckon on 指望)",
    "recognition": "n.承认；认可；识别",
    "reconcile": "v.使和解，调和(reconcile with)",
    "recovery": "n.恢复，康复；找回",
    "recur": "v.再发生，反复出现",
    "refer": "v.参考(refer to)；提及；提交",
    "reflect": "v.反映，表现；反思(reflect on)",
    "reform": "n./v.改革，改造",
    "refrain": "v.克制，忍住(refrain from)",
    "refuge": "n.避难所；v.避难(take refuge in)",
    "refund": "n./v.退款，退还",
    "refute": "v.驳斥，反驳",
    "regime": "n.政权，政体；管理体制",
    "register": "v./n.登记，注册",
    "regulate": "v.调节，控制；管理",
    "reign": "n.统治时期；v.统治，支配",
    "reinforce": "v.加强，增援；强化",
    "reject": "v.拒绝；排斥；n.废品",
    "relate": "v.相关(relate to)；讲述",
    "relay": "v.传递，转播；n.接力赛",
    "release": "v./n.释放；发布；解脱",
    "relevant": "adj.相关的(relevant to)",
    "reliance": "n.依赖，信赖(reliance on)",
    "relief": "n.减轻，宽慰；救济品",
    "relieve": "v.减轻，缓解；换班",
    "reluctant": "adj.不情愿的，勉强的(reluctant to)",
    "rely": "v.依赖，信赖(rely on)",
    "remainder": "n.剩余物；余数",
    "remedy": "n.补救方法；v.纠正，补救",
    "remote": "adj.遥远的；疏远的；渺茫的",
    "render": "v.使成为，致使；给予；翻译",
    "renew": "v.更新；续期；重新开始",
    "renovate": "v.翻新，修复",
    "repel": "v.击退；使厌恶；排斥",
    "reputation": "n.名誉，名声",
    "resemble": "v.像，类似",
    "resent": "v.憎恨，怨恨",
    "reserve": "v.预订；保留；n.储备物；保护区",
    "resign": "v.辞职；顺从(resign oneself to)",
    "resist": "v.抵抗；抵制，忍住",
    "resolution": "n.决心；解决；分辨率",
    "resolve": "v.解决；决定(resolve to do)",
    "resort": "n.度假地；手段；v.诉诸(resort to)",
    "respective": "adj.各自的, 分别的",
    "restore": "v.恢复；修复；归还",
    "restrain": "v.抑制，约束(restrain from)",
    "restrict": "v.限制，约束",
    "resume": "v.重新开始，恢复；n.简历",
    "retain": "v.保持，保留；记住",
    "retreat": "v./n.撤退，退却",
    "reveal": "v.揭示，揭露；展现",
    "revenue": "n.收入，税收",
    "reverse": "v.倒转，逆转；adj.相反的；n.反面",
    "revise": "v.修改，修订；复习",
    "revive": "v.(使)复苏，复兴",
    "revolve": "v.旋转(revolve around 围绕…转)",
    "reward": "n./v.奖励，回报",
    "rigid": "adj.僵硬的；死板的，严格的",
    "rival": "n.竞争对手；adj.竞争性的",
    "rout": "n.溃败；v.彻底击败",
    "routine": "n.常规，例行程序；adj.常规的",
    "royal": "adj.皇家的，王室的",
    "ruin": "n./v.毁灭，崩溃",
    "rumor": "n.谣言，传闻",

    # ---- S ----
    "sacrifice": "v./n.牺牲，献祭",
    "sanction": "n.制裁(pl.)；批准；v.批准",
    "saturate": "v.使饱和(saturate with)；浸透",
    "scale": "n.规模(on a large scale)；等级；比例尺",
    "scan": "v.扫描；浏览；n.扫描",
    "scandal": "n.丑闻",
    "scarce": "adj.稀缺的，不足的",
    "scatter": "v.散开，分散",
    "schedule": "n.时间表，日程；v.安排",
    "scheme": "n.计划，方案；阴谋",
    "scope": "n.范围，视野；机会",
    "scrutiny": "n.仔细检查，审查",
    "sector": "n.领域，部门；扇形",
    "secure": "adj.安全的；v.获得；固定",
    "segment": "n.部分，片段；v.分割",
    "sensation": "n.感觉；轰动，引起轰动的人/事",
    "sensible": "adj.明智的；可感知的",
    "sensitive": "adj.敏感的(sensitive to)；体贴的",
    "sentiment": "n.情绪，看法",
    "sequence": "n.顺序，连续；一系列",
    "setback": "n.挫折，阻碍",
    "severe": "adj.严重的；严厉的；剧烈的",
    "shatter": "v.粉碎，破碎；使震惊",
    "shelter": "n.庇护所；v.庇护，躲避",
    "shield": "n.盾牌，防护物；v.保护(shield from)",
    "shrink": "v.收缩，缩小；退缩(shrink from)",
    "signature": "n.签名，签字；鲜明特色",
    "significance": "n.重要性，意义",
    "significant": "adj.重大的；显著的；有意义的",
    "signify": "v.表示，意味；要紧",
    "simplicity": "n.简单，简朴",
    "simplify": "v.简化",
    "simulate": "v.模拟；假装",
    "simultaneous": "adj.同时发生的",
    "situated": "adj.位于…的；处于…情况的",
    "skeptical": "adj.怀疑的(skeptical about/of)",
    "sketch": "n.草图，速写；简述",
    "slot": "n.狭槽；时间空档；v.插入",
    "slump": "v./n.暴跌，衰退；消沉",
    "soak": "v.浸泡(soak up 吸收)",
    "soar": "v.猛增，高涨；翱翔",
    "sole": "adj.唯一的；n.脚底",
    "solemn": "adj.庄严的，严肃的",
    "solidarity": "n.团结，一致",
    "sophisticated": "adj.精密的，复杂的；老练的",
    "sovereign": "n.君主；adj.主权的",
    "span": "n.跨度，一段时间(attention span 注意力持续期)；v.跨越",
    "spark": "n.火花；导火索；v.引发",
    "specify": "v.具体说明，指定",
    "spectrum": "n.光谱；范围，幅度",
    "speculate": "v.推测；投机(speculate on/about)",
    "sphere": "n.球体；领域，范围",
    "spill": "v./n.溢出，洒出",
    "splash": "v./n.飞溅，泼洒；引起轰动(make a splash)",
    "splendid": "adj.极好的，辉煌的",
    "split": "v./n.分裂，分开(split up)",
    "spoil": "v.破坏；宠坏；n.战利品(pl.)",
    "sponsor": "n.赞助商；v.赞助，主持",
    "spontaneous": "adj.自发的，自然产生的",
    "spot": "n.地点；斑点；v.发现，认出",
    "squeeze": "v.挤压；压缩；n.经济拮据",
    "stability": "n.稳定，稳固",
    "stake": "n.利害关系(at stake 危如累卵)；赌注",
    "startle": "v.使惊吓，使吃惊",
    "starve": "v.(使)饥饿，饿死(starve for 渴望)",
    "statistic": "n.统计数据；adj.统计的",
    "status": "n.地位，身份；状况",
    "steer": "v.驾驶（船/车）；引导(steer clear of 避开)",
    "stem": "n.茎，干；v.起源于(stem from)",
    "stereotype": "n.刻板印象，成见",
    "stern": "adj.严厉的，严峻的",
    "stimulate": "v.刺激，激发，促进",
    "stipulate": "v.规定，约定",
    "stock": "n.库存；股票(stock market)；v.备有",
    "straightforward": "adj.直截了当的，简单的",
    "strategy": "n.战略，策略",
    "streamline": "v.精简，使效率更高",
    "stride": "n.大步(stride forward 大步前进)；进展",
    "striking": "adj.引人注目的，显著的",
    "strive": "v.努力，奋斗(strive for/after)",
    "stroll": "v./n.散步，溜达",
    "structural": "adj.结构性的",
    "stubborn": "adj.固执的；难以处理的",
    "submit": "v.提交；服从(submit to)",
    "subordinate": "adj.下级的(subordinate to)；n.下级",
    "subscribe": "v.订阅；同意(subscribe to)；捐款",
    "subsequent": "adj.随后的(subsequent to)",
    "subsidy": "n.补贴，津贴",
    "substance": "n.物质；实质(in substance)；重要性",
    "substantial": "adj.大量的；重大的；牢固的",
    "substantiate": "v.证实，证明",
    "substitute": "n.替代品；v.替代(substitute for)",
    "subtle": "adj.微妙的；精细的；敏锐的",
    "subtract": "v.减去(subtract from)",
    "succession": "n.连续(in succession)；继承",
    "sue": "v.起诉，控告(sue for)",
    "suffice": "v.足够(suffice it to say 只需说)",
    "suicide": "n.自杀；自取灭亡",
    "summit": "n.峰会；顶峰，顶点",
    "summon": "v.召唤，召集；鼓起（勇气）",
    "superb": "adj.极好的，一流的",
    "superficial": "adj.表面的，肤浅的",
    "superior": "adj.上级的(superior to 优于)；n.上级",
    "supervise": "v.监督，管理",
    "supplement": "n.补充物；增刊；v.补充",
    "suppress": "v.镇压；抑制；隐瞒",
    "supreme": "adj.最高的，至高无上的",
    "surge": "n./v.激增，急剧上升；汹涌",
    "surpass": "v.超过，超越",
    "surplus": "n.剩余，盈余；adj.过剩的",
    "surrender": "v./n.投降，屈服(surrender to)",
    "survey": "n./v.调查；测量；概览",
    "survival": "n.幸存，生存(survival of the fittest)",
    "suspect": "v.怀疑；n.嫌疑人",
    "suspend": "v.暂停；悬挂；使停职",
    "suspicion": "n.怀疑，猜疑",
    "sustain": "v.维持，支撑；遭受；认可",
    "swallow": "v.吞咽；忍受；n.燕子",
    "swear": "v.发誓(swear to)；咒骂",
    "swing": "v./n.摇摆，摆动；转向(in full swing 如火如荼)",
    "switch": "v.转换(switch to/off/on)；n.开关；转变",
    "symbol": "n.象征，符号",
    "sympathy": "n.同情，赞同(in sympathy with)",
    "symptom": "n.症状；征兆",
    "synthesis": "n.综合，合成",
    "systematic": "adj.系统的，有计划的",

    # ---- T ----
    "tackle": "v.处理，解决；n.用具",
    "tactic": "n.策略，手段",
    "tame": "adj.温顺的；平淡的；v.驯服",
    "tangle": "v./n.缠绕，纠结(tangled in)",
    "tariff": "n.关税；价目表",
    "tedious": "adj.单调乏味的，冗长的",
    "temper": "n.脾气，情绪(lose one's temper)；v.使缓和",
    "temporary": "adj.暂时的",
    "tempt": "v.吸引，诱惑(tempt sb into doing)",
    "tendency": "n.趋势，倾向",
    "tender": "adj.温柔的；嫩的；v.投标；提供",
    "tension": "n.紧张，张力",
    "terminal": "n.终端；终点站；adj.末期的",
    "terminate": "v.终止，结束",
    "terrain": "n.地形，地势",
    "terrific": "adj.极好的；巨大的",
    "terrify": "v.使恐惧，使惊吓",
    "testify": "v.作证；证明(testify to)",
    "textile": "n.纺织品",
    "theme": "n.主题，主旨",
    "therapy": "n.治疗，疗法",
    "thereafter": "adv.此后",
    "threshold": "n.门槛，开端(on the threshold of)",
    "thrill": "n.激动；v.使激动",
    "thrive": "v.繁荣，兴旺(thrive on)",
    "thrust": "v./n.猛推；刺；要旨",
    "tide": "n.潮汐；趋势，潮流(tide over 渡过难关)",
    "toil": "n./v.辛苦劳动",
    "tolerate": "v.容忍，忍受",
    "toll": "n.伤亡人数(take its toll)；通行费",
    "torture": "n./v.折磨，痛苦",
    "toss": "v.抛，掷；辗转反侧(toss and turn)",
    "toxic": "adj.有毒的，有害的",
    "trace": "v.追踪，追溯(trace back to)；n.痕迹",
    "trail": "n.小径；痕迹；v.跟踪，落后(trail behind)",
    "trait": "n.特征，特点",
    "transaction": "n.交易；办理",
    "transcend": "v.超越，超出",
    "transfer": "v./n.转移，调动；转账",
    "transform": "v.使改变，变革",
    "transient": "adj.短暂的，瞬息的",
    "transmit": "v.传播，传输；传递",
    "transparent": "adj.透明的；显而易见的",
    "trap": "n.陷阱；v.困住，使陷入",
    "treasure": "n.财富，珍品；v.珍惜",
    "treaty": "n.条约，协议",
    "tremendous": "adj.巨大的，极大的",
    "trend": "n.趋势，潮流",
    "trial": "n.审判；试验，试用(trial and error)",
    "tribe": "n.部落，族群",
    "tribute": "n.致敬(pay tribute to)；贡品",
    "trigger": "n.扳机；诱因；v.引发，触发",
    "trim": "v.修剪；削减；adj.整齐的",
    "triple": "adj.三倍的；v.(使)成为三倍",
    "triumph": "n./v.胜利，成功(triumph over)",
    "trivial": "adj.琐碎的，不重要的",
    "tuition": "n.学费；教学",
    "tune": "n.曲调；v.调整(tune in 收听/in tune with 一致)",
    "turbulent": "adj.动荡的；汹涌的",
    "twist": "v./n.扭曲，弯曲；转折",

    # ---- U ----
    "ultimate": "adj.最终的，终极的",
    "unanimous": "adj.一致同意的",
    "undergo": "v.经历，承受",
    "underline": "v.强调；在…下面划线",
    "undermine": "v.逐渐削弱，暗中破坏",
    "undertake": "v.承担，着手做(undertake to do)",
    "undo": "v.解开，松开；使恢复原状",
    "unfold": "v.展开；展现，发展",
    "unify": "v.统一，联合",
    "unique": "adj.唯一的，独特的(unique to)",
    "universal": "adj.普遍的；全世界的",
    "update": "v./n.更新",
    "upgrade": "v./n.升级，提升",
    "uphold": "v.支持，维护（原则/法律）",
    "upright": "adj.直立的；正直的",
    "uproar": "n.骚动，喧嚣",
    "upset": "v.使不安，打乱",
    "urban": "adj.城市的，都市的",
    "urge": "v.催促，力劝(urge sb to do)；n.强烈欲望",
    "utilize": "v.利用，使用",
    "utter": "v.说，表达；adj.完全的(utter nonsense)",
    "utmost": "adj.最大的，极度的(do one's utmost) 竭尽全力",

    # ---- V ----
    "vacant": "adj.空的，空缺的；茫然的",
    "vague": "adj.模糊的，不明确的",
    "vain": "adj.徒劳的(in vain 白费)；自负的",
    "valid": "adj.有效的；合理的",
    "vanish": "v.消失，消散",
    "variable": "adj.多变的；n.变量",
    "vast": "adj.广阔的；巨大的",
    "venture": "n.冒险事业(joint venture 合资企业)；v.冒险",
    "verbal": "adj.口头的；文字的",
    "verdict": "n.裁决，判决",
    "verify": "v.核实，证实",
    "versatile": "adj.多才多艺的；多功能的",
    "versus": "prep.对，与…相对(vs.)",
    "vessel": "n.船只；容器；血管",
    "veto": "n./v.否决，禁止",
    "vibrate": "v.(使)振动，摇摆",
    "vicious": "adj.恶毒的；凶猛的(vicious circle 恶性循环)",
    "vigorous": "adj.精力充沛的；有力的",
    "violate": "v.违反，侵犯",
    "virtual": "adj.实质上的，事实上的；虚拟的",
    "virtue": "n.美德，优点(by virtue of 由于)",
    "visible": "adj.看得见的，明显的",
    "vision": "n.视力；远见，愿景",
    "vital": "adj.至关重要的，生死攸关的",
    "vivid": "adj.生动的，鲜明的",
    "vocation": "n.职业，使命",
    "void": "adj.空的；无效的(null and void 无效)",
    "volume": "n.音量；卷，册；数量，容量",
    "voluntary": "adj.自愿的，志愿的",
    "vulgar": "adj.粗俗的，庸俗的",
    "vulnerable": "adj.脆弱的，易受伤的(vulnerable to)",
    "vivid": "adj.生动的，鲜明的",
    "vacuum": "n.真空(a vacuum of 缺乏)",

    # ---- W ----
    "wage": "n.工资(pl.)；v.发动（战争/运动） 【熟词僻义：v.发动】",
    "wander": "v.漫步，徘徊；走神",
    "warrant": "v.使有必要，保证；n.授权令",
    "weary": "adj.疲惫的；令人厌倦的",
    "welfare": "n.福利；幸福( welfare system 福利制度)",
    "whereas": "conj.然而，但是，鉴于",
    "whip": "v.鞭打；猛地移动；n.鞭子",
    "wholesale": "adj.批发的；大规模的",
    "wholesome": "adj.有益健康的；有益的",
    "widespread": "adj.广泛分布的，普遍的",
    "wit": "n.才智(at one's wit's end 束手无策)",
    "withdraw": "v.撤回，撤离(withdraw from)",
    "witness": "n.目击者，证人；v.目睹，见证",
    "worship": "n./v.敬仰，崇拜",
    "worthwhile": "adj.值得做的",
    "wreck": "n.残骸；v.破坏，毁坏",

    # ---- Y / Z ----
    "yield": "v.产出；屈服(yield to)；n.产量 【熟词僻义：屈服】",
    "zone": "n.地区，地带；v.使分区",
    "zoom": "v.快速移动；猛增；n.(镜头)变焦",
}

# 去重并排序
all_words = {}
for k, v in KAOYAN_VOCAB.items():
    all_words[k.lower()] = v

# ============================================================
# API 数据获取
# ============================================================

FREE_DICT_API = "https://api.dictionaryapi.dev/api/v2/entries/en/"


def fetch_dictionary(word: str) -> dict | None:
    """从免费词典 API 获取单词数据（音标 + 英文释义 + 近义词）"""
    try:
        resp = httpx.get(FREE_DICT_API + word, timeout=10)
        if resp.status_code != 200:
            return None
        data = resp.json()
        if not data or not isinstance(data, list):
            return None
        entry = data[0]

        # 提取音标
        phonetic_uk = ""
        phonetic_us = ""
        for p in entry.get("phonetics", []):
            text = p.get("text", "")
            audio = p.get("audio", "")
            if not text:
                continue
            # 区分英美音
            if "uk" in str(audio).lower() or "uk" in str(p).lower():
                phonetic_uk = text
            elif "us" in str(audio).lower() or "us" in str(p).lower():
                phonetic_us = text
            elif not phonetic_uk:
                phonetic_uk = text  # 第一个默认为英音

        # 提取英文释义和近/反义词
        definitions = []
        synonyms = []
        antonyms = []
        for meaning in entry.get("meanings", []):
            pos = meaning.get("partOfSpeech", "")
            syns = meaning.get("synonyms", [])
            ants = meaning.get("antonyms", [])
            if syns:
                synonyms.extend(syns[:3])
            if ants:
                antonyms.extend(ants[:3])

            for d in meaning.get("definitions", []):
                en_def = d.get("definition", "")
                if en_def:
                    definitions.append({"pos": pos, "meaning": en_def})

        return {
            "phonetic_uk": phonetic_uk,
            "phonetic_us": phonetic_us,
            "definitions": definitions[:6],  # 最多6条英文释义
            "synonyms": list(set(synonyms))[:6],
            "antonyms": list(set(antonyms))[:6],
        }
    except Exception as e:
        return None


def parse_cn_definition(cn_def_str: str) -> list[dict]:
    """解析中文释义字符串为结构化定义"""
    # 例如: "v.放弃，抛弃；n.放纵，放任 【熟词僻义：放纵】"
    results = []
    # 移除备注
    cn_def_str = re.sub(r'【.*?】', '', cn_def_str).strip()
    # 按分号或换行分割
    parts = re.split(r'[;；]', cn_def_str)
    for part in parts:
        part = part.strip()
        if not part:
            continue
        # 尝试提取词性
        m = re.match(r'^([a-z]+\.)\s*(.+)', part, re.IGNORECASE)
        if m:
            results.append({"pos": m.group(1), "meaning": m.group(2).strip()})
        else:
            # 没有词性标注，继承上一个词性或留空
            results.append({"pos": "", "meaning": part})
    return results


def build_word_entry(word: str, cn_def: str, dict_data: dict | None) -> dict:
    """构建完整的单词词条"""
    cn_defs = parse_cn_definition(cn_def)

    # 合并中英文释义
    definition = json.dumps(cn_defs, ensure_ascii=False)

    # 处理音标
    phonetic_uk = ""
    phonetic_us = ""
    if dict_data:
        phonetic_uk = dict_data.get("phonetic_uk", "")
        phonetic_us = dict_data.get("phonetic_us", "")

    # 处理近反义词
    synonyms = []
    antonyms = []
    if dict_data:
        synonyms = dict_data.get("synonyms", [])
        antonyms = dict_data.get("antonyms", [])

    # 判断是否为熟词僻义
    category = "rare" if "熟词僻义" in cn_def else "core"

    # 估测考频（基于词长和常见度粗略估计，后续可调整）
    frequency = 4 if category == "core" else 5

    return {
        "word": word,
        "phonetic_uk": phonetic_uk,
        "phonetic_us": phonetic_us,
        "definition": definition,
        "exam_type": "kaoyan",
        "category": category,
        "frequency": frequency,
        "etymology": "",
        "example_sentences": "[]",
        "synonyms": json.dumps(synonyms, ensure_ascii=False) if synonyms else "[]",
        "antonyms": json.dumps(antonyms, ensure_ascii=False) if antonyms else "[]",
    }


# ============================================================
# 主流程
# ============================================================

def main():
    import argparse
    parser = argparse.ArgumentParser(description="考研核心词库自动生成器")
    parser.add_argument("--count", type=int, default=0, help="生成数量（0=全部）")
    parser.add_argument("--batch", type=str, default="", help="指定批次字母（如 A）")
    parser.add_argument("--no-api", action="store_true", help="跳过在线词典API，仅用内置释义")
    parser.add_argument("--output", type=str, default="", help="输出文件路径")
    args = parser.parse_args()

    # 筛选词汇
    word_list = list(all_words.items())
    if args.batch:
        letter = args.batch.upper()
        word_list = [(w, d) for w, d in word_list if w[0].upper() == letter]
    if args.count and args.count < len(word_list):
        word_list = word_list[:args.count]

    total = len(word_list)
    print(f"📚 考研核心词库生成器")
    print(f"   目标词汇: {total} 个")
    print(f"   在线查词: {'关闭' if args.no_api else '开启 (dictionaryapi.dev)'}")
    print()

    generated = []
    api_success = 0
    api_fail = 0

    for i, (word, cn_def) in enumerate(word_list):
        dict_data = None
        if not args.no_api:
            try:
                dict_data = fetch_dictionary(word)
                if dict_data:
                    api_success += 1
                else:
                    api_fail += 1
                # 礼貌限速，每词间隔0.5秒
                if (i + 1) % 5 == 0:
                    time.sleep(1.0)
                else:
                    time.sleep(0.3)
            except Exception:
                api_fail += 1

        entry = build_word_entry(word, cn_def, dict_data)
        generated.append(entry)

        # 进度显示
        ph = "🔊" if dict_data and dict_data.get("phonetic_uk") else "  "
        syn = "📎" if dict_data and dict_data.get("synonyms") else "  "
        status = f"{ph}{syn}"
        if (i + 1) % 20 == 0 or i == 0 or i == total - 1:
            print(f"  [{i+1:4d}/{total}] {status} {word}")

    print()
    print(f"✅ 生成完成: {len(generated)} 个词条")
    if not args.no_api:
        print(f"   🔊 获取到音标: {api_success} 词")
        print(f"   ❌ 未获取到: {api_fail} 词")

    # 保存
    output_path = Path(args.output) if args.output else KAOYAN_WORDS_FILE
    DATA_DIR.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w", encoding="utf-8") as f:
        json.dump(generated, f, ensure_ascii=False, indent=2)

    print(f"📄 已保存至: {output_path}")

    # 提示下一步
    if output_path.name == "kaoyan.json":
        print()
        print("💡 下一步：运行导入脚本将词库写入数据库")
        print("   python scripts/init_data.py")
        print("   (或) python scripts/import_user_wordlist.py --file data/kaoyan.json")


if __name__ == "__main__":
    main()
